### ISSUE TITLE
Support POST/PUT test cases with different content.

### ISSUE THREAD

**Issue by nocodehummel** [gadicc/fetch-mock-cache#6]
The cache could better support POST/PUT TDD by including `body=<hash>` in the filename. A similar approach as with headers to support different test cases.

**Comment by gadicc** [comment]
Agree 100%.  Do you currently need this for anything?  Will try prioritise this week if so.

**Comment by nocodehummel** [comment]
Not a priority for me. Just a suggestion.

**Comment by gadicc** [comment]
Ok, perfect, thanks.  A very welcome suggestion :pray: :grin:

**Comment by ismaelga** [comment]
I assumed this was already supported 😓 got me by surprise really
Any plans on supporting this?

**Comment by gadicc** [comment]
Is "planned", yes `:)  But will prioritize it now that someone actually needs it for something.  I should have some time next week to do this.  Watch this space :)

**Comment by ismaelga** [comment]
That's great @gadicc 
I just created a store to handle this. Hope these changes don't affect it 😅 

I'm afraid I won't have time to test your changes anytime soon

My workaround:
```js
import NodeFS from 'jest-fetch-mock-cache/lib/stores/nodeFs'

function hash(content: any) {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const crypto = require('crypto')
  return crypto.createHash('md5').update(content).digest('hex')
}

class MyStore extends NodeFS {
  async idFromResponse(request: Request): Promise<string> {
    // const headers = JSON.stringify(Object.fromEntries(request.headers.entries()))
    const body = request.body ? hash(request.body) : ''
    const url = new URL(request.url)
    const id = (url.hostname + url.pathname + url.search + '__' + body + '.json').replaceAll(
      '/',
      '-',
    )
    return id
  }
}

import fetchMock from 'jest-fetch-mock'
import createCachingMock from 'jest-fetch-mock-cache'

export function startMock() {
  const cachingMock = createCachingMock({ store: new MyStore({}) })
  fetchMock.mockImplementation(cachingMock)
}
```

**Comment by gadicc** [comment]
Thanks for your near instant reply, @ismaelga, and sorry I'm a bit slower `:)

1) Great that you got this working so quickly on your own and means I did a good job with the Storage API (i think `;)).

2) Regrettably I did make some breaking changes in dev, I better think if I'll need to publish as a new major version, didn't actually think anyone else was using the Storage API yet.  It includes a bunch of improvements though that make the API clearer and easier to use (and I guess anyway, you won't need your `MyStore` as the existing store now handles this case :sweat_smile:)

No worries about not having time to test, I'll do a bit more on my side and publish when I'm satisfied.  I'll tag you here regardless to let you know how the upgrade will affect you :sweat_smile:

**Comment by gadicc** [comment]
Update:

* Published and well tested in the new major `v2`
* Not published to `v1` since the Storage API changed.  @ismaelga, that means your new store won't work in the new version, however, since all you added was POST support, you won't need it either `:)
